CREATE DATABASE IF NOT EXISTS cartdb;
CREATE DATABASE IF NOT EXISTS orderdb;
CREATE DATABASE IF NOT EXISTS productdb;
CREATE DATABASE IF NOT EXISTS userdb;
GRANT ALL PRIVILEGES ON cartdb.* TO 'mysql'@'%';
GRANT ALL PRIVILEGES ON orderdb.* TO 'mysql'@'%';
GRANT ALL PRIVILEGES ON productdb.* TO 'mysql'@'%';
GRANT ALL PRIVILEGES ON userdb.* TO 'mysql'@'%';
FLUSH PRIVILEGES;
